// UI copy for the live demos. Agent replies themselves come from the services.

export const COPY = {
  ru: {
    common: {
      label: 'Живое демо',
      checking: 'проверяем сервис',
      up: 'онлайн',
      degraded: 'запущен, но не готов',
      down: 'офлайн',
      note: (repo) => `Каждый запрос уходит в настоящий ${repo} через серверный мост — ключи остаются на сервере.`,
      offTitle: 'Сервис сейчас выключен',
      offBody: 'Это демо работает только с настоящим сервисом, а он сейчас не запущен. Напишите мне — покажу всё вживую на созвоне.',
      degradedTitle: 'Сервис запущен, но не готов',
      degradedBody: 'Процесс отвечает, но не готова его зависимость — база данных, языковая модель или ops-core-api.',
      retry: 'Проверить снова',
      write: 'Написать мне',
      hint: (repo) => `${repo}: docker compose up`,
      you: 'Вы',
      send: 'Отправить',
      enter: 'Enter — отправить',
      try: 'Попробуйте',
      restart: 'Начать заново',
      fail: {
        unreachable: 'Сервис не ответил. Проверьте, что он запущен, и отправьте ещё раз.',
        timeout: 'Сервис думает дольше обычного — языковая модель на первом запросе бывает медленной. Попробуйте ещё раз.',
        rate_limited: 'Слишком много запросов подряд — сервис намеренно притормаживает. Подождите пару секунд.',
        media: 'Сервис ответил, но аудиосоединение (WebRTC) не установилось. Чаще всего мешает VPN или защита от утечки WebRTC в браузере — попробуйте без них.',
        upstream: (s) => `Сервис ответил ${s}. Подробности — в его логах.`,
      },
    },
    rag: {
      emptyTitle: 'Спросите клинику о чём угодно',
      emptyBody: 'База знаний — пять документов клиники Aurora: правила отмены, услуги, часы работы, оплата, первый визит.',
      placeholder: 'Вопрос про правила, цены или услуги…',
      cta: 'Спросить',
      thinking: 'Ищем в документах…',
      suggestions: ['Как отменить запись?', 'Есть ли парковка?', 'Что взять с собой на первый визит?', 'Какая погода на Марсе?'],
      answer: 'Ответ',
      sourcesTitle: 'Источники',
      sourcesLede: 'Найдены до того, как модель начала писать ответ. Документы на английском — поиск работает по смыслу, а не по словам.',
      sourcesIdle: 'Задайте вопрос — здесь появятся фрагменты, на которых построен ответ.',
      refused: 'Модель не вызывалась: ни один фрагмент не прошёл порог уверенности. Сервис честно отказался вместо того, чтобы угадывать.',
      chunk: (i) => `фрагмент ${i + 1}`,
      metaAnswer: (s, n) => `${s} · опирается на ${n} фрагм.`,
      metaRefused: (s) => `${s} · без вызова модели`,
    },
    sales: {
      who: 'Вы пишете Алексу — он продаёт пакеты процедур клиники Aurora Wellness. Цены он берёт из ops-core-api.',
      rail: 'Этап разговора — его возвращает сервис',
      stages: {
        greeting: ['Приветствие', 'Знакомится'],
        qualify: ['Уточнение', 'Выясняет потребность'],
        present: ['Предложение', 'Называет реальную цену'],
        objection_handling: ['Возражение', 'Отрабатывает сомнение'],
        upsell: ['Допродажа', 'Предлагает пакет выгоднее'],
        close: ['Закрытие', 'Доводит до решения'],
      },
      placeholder: 'Напишите Алексу…',
      thinking: 'Алекс печатает…',
      nextLabel: 'Вариант ответа',
      // the customer's side of a happy path; a line already said is never offered again
      next: {
        start: ['Здравствуйте! Постоянно забиваются мышцы в плечах', 'Привет! Хочу восстановиться после тренировок'],
        greeting: ['Постоянно забиваются мышцы в плечах', 'Хочу восстановиться после тренировок'],
        qualify: ['Думаю, глубокий массаж, сеанса три', 'Сидячая работа — к вечеру шея как камень', 'Давайте три сеанса'],
        presentAsk: ['Сколько это будет стоить?', 'Хорошо, что вы предложите?'],
        present: ['Хм, дороговато выходит', 'Звучит хорошо'],
        objection_handling: ['Ладно, убедили', 'Всё равно дороговато'],
        upsell: ['Давайте шесть сеансов', 'Нет, оставлю как есть'],
        close: ['Да, как записаться?', 'Отлично, записывайте'],
      },
      // when Alex stays on the same stage after a reply: lines that keep moving, never the alternative just declined
      again: {
        qualify: ['Глубокий массаж, сеанса три', 'А что вы посоветуете?'],
        presentAsk: ['Сколько это будет стоить?'],
        present: ['Звучит хорошо', 'Давайте оформим'],
        objection_handling: ['Ладно, убедили'],
        upsell: ['Да, оформляйте', 'Как записаться?'],
        close: ['Спасибо!', 'Да, всё верно'],
      },
      done: 'Разговор закрыт',
      handoffTitle: 'Передано человеку',
      handoffBody: 'Агент несколько раз не понял собеседника и остановился, а не пошёл по кругу. Так задумано: дальше подключается специалист.',
    },
    mcp: {
      intro: 'Агент сам решает, какие инструменты вызвать. Каждый шаг — настоящее событие из потока SSE, в том порядке, в каком всё происходило.',
      placeholder: 'Дайте агенту задачу…',
      cta: 'Запустить',
      running: 'Агент работает…',
      idle: 'Консоль пустая. Выберите задачу ниже — лучше ту, где нужно несколько инструментов.',
      suggestions: [
        'Найди Tom Okafor и отправь ему расчёт на 6 сеансов глубокого массажа',
        'Свободен ли завтра столик на 18:00? И найди клиента Anna Petrova',
        'Сколько стоит глубокий массаж за шесть сеансов?',
      ],
      call: 'вызов',
      result: 'результат',
      final: 'ответ',
      error: 'ошибка',
      toolError: 'инструмент вернул ошибку',
      clear: 'Очистить',
    },
    voice: {
      who: 'Вы звоните Миле — она принимает брони столиков в ресторане Aurora. Настоящий звонок: WebRTC, распознавание и синтез речи.',
      start: 'Позвонить Миле',
      askingMic: 'Ждём доступ к микрофону…',
      micDeniedTitle: 'Без микрофона разговора не выйдет',
      micDeniedBody: 'Разрешите микрофон для этого сайта в настройках браузера рядом с адресной строкой и позвоните снова.',
      connecting: 'Соединяем…',
      live: 'Идёт разговор',
      liveHint: 'Просто говорите — Мила ответит, когда вы закончите.',
      joining: 'Мила подключается — первый звонок загружает модель распознавания…',
      pickingUp: 'Мила берёт трубку…',
      end: 'Завершить',
      endedTitle: 'Разговор окончен',
      endedBody: 'Всё, что Мила забронировала, уже лежит в ops-core-api — это видно в демо операционного ядра.',
      again: 'Позвонить ещё раз',
      droppedTitle: 'Связь оборвалась',
      droppedBody: 'Комната закрылась не по вашей команде — скорее всего, остановился сервер LiveKit.',
      failedTitle: 'Не удалось подключиться',
      noAgent: 'Вы в комнате, но Мила не пришла — не запущен голосовой воркер (контейнер voice-agent).',
      audioBlocked: 'Браузер придерживает звук, пока вы не разрешите.',
      unlock: 'Включить звук',
      tryLabel: 'Попробуйте сказать',
      tryLines: ['Столик на четверых завтра на семь', 'А есть что-нибудь пораньше?', 'Давайте лучше в пятницу'],
      you: 'Вы',
      agent: 'Мила',
      transcript: 'Расшифровка',
    },
    core: {
      intro: 'Источник правды для всех четырёх агентов. Здесь можно отправить настоящие запросы к его API.',
      fleet: 'Готовность всех сервисов',
      fleetNote: 'GET /health/ready · обновляется каждые 10 секунд',
      // one short line each: the fleet cells keep a fixed height
      roles: {
        core: 'Брони, клиенты, цены',
        rag: 'Ответы по документам',
        sales: 'Диалог продаж',
        mcp: 'Инструменты агента',
        voice: 'Голосовые звонки',
      },
      states: { checking: 'проверяем', up: 'готов', degraded: 'не готов', down: 'офлайн' },
      endpoints: {
        slots: 'Свободные слоты',
        customers: 'Поиск клиента',
        quote: 'Расчёт цены',
        search: 'Поиск по смыслу',
        conflict: 'Сценарий: двойная бронь',
      },
      fields: { date: 'Дата', resource: 'Ресурс', name: 'Имя', service: 'Услуга', quantity: 'Количество', query: 'Запрос', top_k: 'Сколько фрагментов' },
      resources: { table: 'Столик', treatment_room: 'Кабинет', meeting_room: 'Переговорная' },
      send: 'Отправить запрос',
      keyNote: 'добавляет сервер',
      responseIdle: 'Отправьте запрос — здесь появится настоящий ответ сервиса.',
      conflictBody: 'Бронируем свободный столик, затем пытаемся занять тот же слот ещё раз и в конце отменяем бронь, чтобы освободить слот. Второй запрос должен получить 409: правило «одна бронь на слот» держат и сервис, и ограничение в базе данных.',
      run: 'Запустить сценарий',
      steps: ['Находим свободный слот', 'Бронируем — ждём 201', 'Повторяем — ждём 409', 'Отменяем — слот снова свободен'],
      noSlot: 'Свободных столиков в ближайшие дни нет — сценарию нечего бронировать.',
    },
  },
  en: {
    common: {
      label: 'Live demo',
      checking: 'checking the service',
      up: 'online',
      degraded: 'running, not ready',
      down: 'offline',
      note: (repo) => `Every request goes to the real ${repo} through a server-side bridge — keys never leave the server.`,
      offTitle: 'The service is switched off right now',
      offBody: "This demo only talks to the real service, and it isn't running at the moment. Get in touch — I'll show it live on a call.",
      degradedTitle: 'Running, but not ready',
      degradedBody: 'The process answers, but something it depends on is down — the database, the language model or ops-core-api.',
      retry: 'Check again',
      write: 'Get in touch',
      hint: (repo) => `${repo}: docker compose up`,
      you: 'You',
      send: 'Send',
      enter: 'Enter to send',
      try: 'Try',
      restart: 'Start over',
      fail: {
        unreachable: "The service didn't answer. Make sure it's running and send again.",
        timeout: 'The service is taking longer than usual — a language model can be slow on the first request. Try again.',
        rate_limited: 'Too many requests in a row — the service is deliberately slowing down. Wait a couple of seconds.',
        media: 'The service answered, but the audio connection (WebRTC) never came up. A VPN or the browser’s WebRTC leak protection is the usual cause — try without them.',
        upstream: (s) => `The service answered ${s}. Its logs have the details.`,
      },
    },
    rag: {
      emptyTitle: 'Ask the clinic anything',
      emptyBody: 'The knowledge base is five documents of the Aurora clinic: cancellations, treatments, opening hours, payment, first visit.',
      placeholder: 'Ask about policies, prices or services…',
      cta: 'Ask',
      thinking: 'Searching the documents…',
      suggestions: ['How do I cancel an appointment?', 'Is there parking?', 'How should I prepare for my first visit?', "What's the weather on Mars?"],
      answer: 'Answer',
      sourcesTitle: 'Sources',
      sourcesLede: 'Retrieved before the model wrote a single word. Search works by meaning, not keywords — ask in any language.',
      sourcesIdle: 'Ask a question — the passages behind the answer will appear here.',
      refused: 'The model was never called: no passage cleared the confidence threshold. The service declined instead of guessing.',
      chunk: (i) => `passage ${i + 1}`,
      metaAnswer: (s, n) => `${s} · grounded in ${n} passages`,
      metaRefused: (s) => `${s} · no model call`,
    },
    sales: {
      who: 'You are chatting with Alex, who sells treatment packages for Aurora Wellness. Prices come from ops-core-api. He replies in the language he is configured with.',
      rail: 'Conversation stage — reported by the service',
      stages: {
        greeting: ['Greeting', 'Says hello'],
        qualify: ['Qualify', 'Finds out the need'],
        present: ['Present', 'Quotes the real price'],
        objection_handling: ['Objection', 'Handles the doubt'],
        upsell: ['Upsell', 'Offers a better-value package'],
        close: ['Close', 'Asks for a decision'],
      },
      placeholder: 'Write to Alex…',
      thinking: 'Alex is typing…',
      nextLabel: 'Reply with',
      next: {
        start: ['Hi! My shoulder muscles keep tightening up', 'Hi! I want to recover after training'],
        greeting: ['My shoulder muscles keep tightening up', 'I want to recover after training'],
        qualify: ['Probably a deep tissue massage, about three sessions', 'Desk job — my neck is stiff by evening', "Let's do three sessions"],
        presentAsk: ['How much would that be?', 'Okay, what do you suggest?'],
        present: ['Hmm, that is a bit pricey', 'Sounds good'],
        objection_handling: ['Okay, you convinced me', 'Still a bit pricey'],
        upsell: ["Let's do six sessions", "No, I'll keep it as is"],
        close: ['Great, how do I book?', 'Perfect, book me in'],
      },
      again: {
        qualify: ['Deep tissue massage, about three sessions', 'What would you recommend?'],
        presentAsk: ['How much would that be?'],
        present: ['Sounds good', "Let's go ahead"],
        objection_handling: ['Okay, you convinced me'],
        upsell: ['Yes, go ahead', 'How do I book?'],
        close: ['Thank you!', 'Yes, that is right'],
      },
      done: 'Conversation closed',
      handoffTitle: 'Handed over to a human',
      handoffBody: 'The agent lost the thread a few times and stopped instead of looping. That is by design: a specialist takes over from here.',
    },
    mcp: {
      intro: 'The agent decides which tools to call on its own. Every step is a real SSE event, shown in the order it happened.',
      placeholder: 'Give the agent a task…',
      cta: 'Run',
      running: 'Agent is working…',
      idle: 'The console is empty. Pick a task below — ideally one that needs several tools.',
      suggestions: [
        'Find Tom Okafor and send him a quote for 6 deep tissue massage sessions',
        'Is a table free tomorrow at 18:00? And look up Anna Petrova',
        'How much are six deep tissue massage sessions?',
      ],
      call: 'call',
      result: 'result',
      final: 'answer',
      error: 'error',
      toolError: 'tool returned an error',
      clear: 'Clear',
    },
    voice: {
      who: 'You are calling Mila, who takes table bookings for the Aurora restaurant. A real call: WebRTC, speech recognition and synthesis.',
      start: 'Call Mila',
      askingMic: 'Waiting for the microphone…',
      micDeniedTitle: 'No microphone, no conversation',
      micDeniedBody: 'Allow the microphone for this site in the browser settings next to the address bar, then call again.',
      connecting: 'Connecting…',
      live: 'On the call',
      liveHint: 'Just talk — Mila answers when you finish.',
      joining: 'Mila is joining — the first call loads the speech model…',
      pickingUp: 'Mila is picking up…',
      end: 'Hang up',
      endedTitle: 'Call ended',
      endedBody: 'Whatever Mila booked is already in ops-core-api — you can see it in the operations core demo.',
      again: 'Call again',
      droppedTitle: 'The line dropped',
      droppedBody: 'The room closed without you hanging up — most likely the LiveKit server stopped.',
      failedTitle: 'Could not connect',
      noAgent: "You are in the room, but Mila didn't join — the voice worker (voice-agent container) isn't running.",
      audioBlocked: 'The browser is holding back audio until you allow it.',
      unlock: 'Enable sound',
      tryLabel: 'Try saying',
      tryLines: ['A table for four tomorrow at seven', 'Anything a little earlier?', "Let's make it Friday instead"],
      // shown when the server can't run this call in English (it reports another language, or none)
      fallbackNote: "This server doesn't run calls in English yet — Mila will answer in Russian. Try saying:",
      fallbackLines: ['Столик на четверых завтра на семь', 'А есть что-нибудь пораньше?', 'Давайте лучше в пятницу'],
      you: 'You',
      agent: 'Mila',
      transcript: 'Transcript',
    },
    core: {
      intro: 'The source of truth for all four agents. Send real requests to its API right here.',
      fleet: 'Readiness of every service',
      fleetNote: 'GET /health/ready · refreshed every 10 seconds',
      roles: {
        core: 'Bookings & pricing',
        rag: 'Document answers',
        sales: 'Sales dialogue',
        mcp: 'Agent tools',
        voice: 'Voice calls',
      },
      states: { checking: 'checking', up: 'ready', degraded: 'not ready', down: 'offline' },
      endpoints: {
        slots: 'Free slots',
        customers: 'Customer search',
        quote: 'Price quote',
        search: 'Semantic search',
        conflict: 'Scenario: double booking',
      },
      fields: { date: 'Date', resource: 'Resource', name: 'Name', service: 'Service', quantity: 'Quantity', query: 'Query', top_k: 'Passages' },
      resources: { table: 'Table', treatment_room: 'Treatment room', meeting_room: 'Meeting room' },
      send: 'Send request',
      keyNote: 'added by the server',
      responseIdle: "Send a request — the service's real response will appear here.",
      conflictBody: 'We book a free table, try to take the same slot again, then cancel to free it. The second request must get a 409: the "one party per slot" rule is enforced by the service and by a database constraint.',
      run: 'Run scenario',
      steps: ['Find a free slot', 'Book — expect 201', 'Book again — expect 409', 'Cancel — the slot is free again'],
      noSlot: 'No free tables in the coming days — nothing for the scenario to book.',
    },
  },
};
